const $ = (s) => document.querySelector(s);
const strengthBar = $('#strengthBar'), scoreText = $('#scoreText'), strengthLabel = $('#strengthLabel');
const criteria = $('#criteria'), suggestionList = $('#suggestionList'), passwordInput = $('#passwordInput');
const common = ['password','123456','qwerty','admin','welcome','letmein','football','iloveyou','india','btech'];
const checks = [{name:'12+ characters',test:p=>p.length>=12},{name:'Uppercase',test:p=>/[A-Z]/.test(p)},{name:'Lowercase',test:p=>/[a-z]/.test(p)},{name:'Number',test:p=>/\d/.test(p)},{name:'Special character',test:p=>/[^A-Za-z0-9]/.test(p)}];
function analyzePassword() {
  const p = passwordInput.value;
  if (!p) { resetAnalysis(); return; }
  let score=0, notes=[]; const hasUpper=/[A-Z]/.test(p),hasLower=/[a-z]/.test(p),hasNum=/\d/.test(p),hasSym=/[^A-Za-z0-9]/.test(p);
  score += Math.min(p.length*4,40); if(hasUpper)score+=12;else notes.push('Add uppercase letters (A–Z).'); if(hasLower)score+=12;else notes.push('Add lowercase letters (a–z).'); if(hasNum)score+=12;else notes.push('Include at least one number.'); if(hasSym)score+=14;else notes.push('Use a special symbol like !, @, or #.');
  if (/(.)\1\1/.test(p)) {score-=12; notes.push('Avoid repeated characters such as “aaa”.');}
  if (/abc|bcd|cde|123|234|345|qwerty/i.test(p)) {score-=13;notes.push('Avoid predictable sequences.');}
  if (common.some(word=>p.toLowerCase().includes(word))) {score-=25; notes.push('Avoid common words or popular passwords.');}
  if(p.length<12) notes.unshift('Increase length to at least 12 characters.');
  score=Math.max(0,Math.min(100,score)); let label, color;
  if(score<35){label='Weak';color='#ef5c5c'}else if(score<60){label='Moderate';color='#ff9c3d'}else if(score<80){label='Strong';color='#f3d75b'}else{label='Very Strong';color='#4bd490'}
  strengthBar.style.width=score+'%';strengthBar.style.background=color;scoreText.textContent=score+'%';strengthLabel.textContent=label;strengthLabel.style.color=color;
  criteria.innerHTML=checks.map(c=>`<span class="${c.test(p)?'yes':''}">${c.test(p)?'✓':'○'} ${c.name}</span>`).join('');
  suggestionList.innerHTML=(notes.length?notes:['Great job! This password has a strong mix of characters. Keep it unique for every account.']).map(n=>`<li>${n}</li>`).join('');
  const variety=[hasUpper,hasLower,hasNum,hasSym].filter(Boolean).length; const entropy=Math.round(p.length*Math.log2(26*(hasUpper?2:1)+26*(hasLower?2:1)+10*(hasNum?1:0)+32*(hasSym?1:0)||1));
  const crack=score<35?'Instantly':score<60?'A few hours':score<80?'Several years':'Centuries';
  $('#passwordStats').innerHTML=`<article><span>▣</span><p>Password length</p><strong>${p.length} characters</strong></article><article><span>◌</span><p>Estimated entropy</p><strong>${entropy} bits</strong></article><article><span>◷</span><p>Estimated crack time</p><strong>${crack}</strong></article><article><span>◈</span><p>Character variety</p><strong>${variety} of 4 types</strong></article>`;
  saveHistory(score); $('#checkedCount').textContent=JSON.parse(localStorage.getItem('cyberShieldHistory')||'[]').length;
}
function resetAnalysis(){strengthBar.style.width='0';scoreText.textContent='0%';strengthLabel.textContent='Waiting for input';strengthLabel.style.color='';criteria.innerHTML='';suggestionList.innerHTML='<li>Enter a password to see tailored advice.</li>';$('#passwordStats').innerHTML=['Password length','Estimated entropy','Crack time','Character variety'].map((x,i)=>`<article><span>${['▣','◌','◷','◈'][i]}</span><p>${x}</p><strong>—</strong></article>`).join('')}
let saveTimeout;function saveHistory(score){clearTimeout(saveTimeout);saveTimeout=setTimeout(()=>{let h=JSON.parse(localStorage.getItem('cyberShieldHistory')||'[]');if(!h.length||h[0].score!==score){h.unshift({score,date:Date.now()});localStorage.setItem('cyberShieldHistory',JSON.stringify(h.slice(0,20)))}} ,700)}
passwordInput.addEventListener('input',analyzePassword);$('#showPassword').onclick=()=>{passwordInput.type=passwordInput.type==='password'?'text':'password'};
$('#lengthRange').oninput=e=>$('#lengthOutput').textContent=e.target.value;
function generatePassword(){let upper='ABCDEFGHJKLMNPQRSTUVWXYZ',lower='abcdefghijkmnopqrstuvwxyz',nums='23456789',symbols='!@#$%&*?+-_';if($('#similar').checked){upper='ABCDEFGHJKMNPQRSTUVWXYZ';lower='abcdefghijkmnpqrstuvwxyz';nums='23456789'}let groups=[];if($('#upper').checked)groups.push(upper);if($('#lower').checked)groups.push(lower);if($('#numbers').checked)groups.push(nums);if($('#symbols').checked)groups.push(symbols);if(!groups.length){toast('Select at least one character set.');return}let out='';groups.forEach(g=>out+=g[Math.floor(Math.random()*g.length)]);let all=groups.join('');while(out.length<+$('#lengthRange').value)out+=all[Math.floor(Math.random()*all.length)];out=out.split('').sort(()=>Math.random()-.5).join('');$('#generatedPassword').textContent=out;toast('Secure password generated!')}
$('#generateBtn').onclick=generatePassword;$('#copyBtn').onclick=async()=>{const text=$('#generatedPassword').textContent;if(text.startsWith('Click'))return toast('Generate a password first.');try{await navigator.clipboard.writeText(text);toast('Password copied to clipboard.')}catch{toast('Copy it manually from the card.')}};
const tips=['Use a different password for every account.','Turn on two-factor authentication (2FA).','Never share your OTP with anyone.','Update your phone and apps regularly.','Check email sender addresses carefully.','Use a password manager for long passwords.','Back up important files in two places.','Avoid banking on public Wi-Fi.','Lock your screen when away from it.','Download apps only from official stores.','Review social media privacy settings.','Think before clicking urgent-looking links.','Log out of shared computers.','Use antivirus software and keep it updated.','Report suspicious emails and messages.'];
$('#tipsGrid').innerHTML=tips.map((t,i)=>`<article><span>${String(i+1).padStart(2,'0')}</span>${t}</article>`).join('');$('#tipsBtn').onclick=()=>{$('#tipsGrid').classList.toggle('open');$('#tipsBtn').innerHTML=$('#tipsGrid').classList.contains('open')?'Hide tips ↑':'Explore 15 tips <b>→</b>'};
const topics={phishing:['Phishing: spot the bait','Phishing messages pretend to be from a bank, college, or delivery service. They often create urgency: “verify now” or “your account will close.”','Check the sender address, never share OTPs or passwords, and type trusted websites directly in the browser.'],malware:['Malware: harmful software','Malware includes viruses, trojans, worms, and spyware. It can damage files, slow devices, or quietly steal information.','Install apps from trusted stores, avoid unknown USB drives, and keep your system and antivirus updated.'],ransomware:['Ransomware: protect your files','Ransomware encrypts your files and asks for payment to unlock them. It often enters through unsafe downloads or email attachments.','Keep regular backups, patch software quickly, and never open unexpected attachments.'],identity:['Identity theft: guard your identity','Identity theft happens when someone uses personal details like Aadhaar data, OTPs, or card information without permission.','Share sensitive data only when necessary, watch account alerts, and use unique passwords.']};
document.querySelectorAll('.learn-btn').forEach(b=>b.onclick=()=>{let t=topics[b.dataset.topic];$('#modalContent').innerHTML=`<h3>${t[0]}</h3><p>${t[1]}</p><p><strong>How to stay safe:</strong> ${t[2]}</p>`;$('#modal').classList.remove('hidden')});$('#modalClose').onclick=()=>$('#modal').classList.add('hidden');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.add('hidden')};
const quiz=[['You receive a bank email asking for your OTP. What should you do?',['Reply with it','Ignore it and contact the bank directly','Forward it to friends','Click the link'],1,'Banks never ask for OTPs by email or phone.'],['What is the safest password practice?',['Reuse one strong password','Use your name and birth year','Use a unique long password for each account','Write passwords in public notes'],2,'Unique passwords limit the impact of one account breach.'],['Two-factor authentication adds:', ['A second independent verification step','A second password to remember','More advertisements','A public account'],0,'2FA combines something you know with a code or device you have.'],['Which is a warning sign of phishing?',['A familiar sender name','A message that creates urgency','A company logo','Correct grammar'],1,'Urgency is commonly used to make people act before thinking.'],['Before connecting to public Wi-Fi, you should:', ['Use it for online banking','Turn off security updates','Avoid sensitive transactions','Share the password publicly'],2,'Public networks can expose sensitive activity; avoid banking and payments.']];
let qi=0,selected=null,quizScore=0;function renderQuiz(){let q=quiz[qi];selected=null;$('#quizProgress').textContent=`Question ${qi+1} of ${quiz.length}`;$('#questionText').textContent=q[0];$('#answers').innerHTML=q[1].map((a,i)=>`<button class="answer" data-i="${i}">${String.fromCharCode(65+i)}. ${a}</button>`).join('');$('#nextBtn').disabled=true;document.querySelectorAll('.quiz-progress i').forEach((x,i)=>x.classList.toggle('active',i<=qi));document.querySelectorAll('.answer').forEach(b=>b.onclick=()=>{if(selected!==null)return;selected=+b.dataset.i;document.querySelectorAll('.answer').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');$('#nextBtn').disabled=false})}function finishQuiz(){let msg=quizScore===5?'Excellent—your cyber instincts are sharp!':quizScore>=3?'Good work! Review the tips above to get even stronger.':'Keep learning—cybersecurity gets better with practice.';$('#quizCard').innerHTML=`<p class="eyebrow">QUIZ COMPLETE</p><h3>You scored <span style="color:var(--cyan)">${quizScore} / ${quiz.length}</span></h3><p style="color:var(--muted);line-height:1.7">${msg}</p><button class="btn primary" id="restartBtn">Try again ↻</button>`;$('#restartBtn').onclick=()=>{qi=0;quizScore=0;$('#quizCard').innerHTML='<div class="quiz-progress"><span id="quizProgress"></span><div><i id="quizStep1"></i><i id="quizStep2"></i><i id="quizStep3"></i><i id="quizStep4"></i><i id="quizStep5"></i></div></div><h3 id="questionText"></h3><div id="answers" class="answers"></div><button id="nextBtn" class="btn primary" disabled>Next question →</button>';renderQuiz();$('#nextBtn').onclick=nextQuestion}}function nextQuestion(){if(selected===quiz[qi][2])quizScore++;qi++;if(qi===quiz.length)finishQuiz();else renderQuiz()}renderQuiz();$('#nextBtn').onclick=nextQuestion;
function toast(text){let t=$('#toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2300)}
$('#checkedCount').textContent=JSON.parse(localStorage.getItem('cyberShieldHistory')||'[]').length;
$('#themeBtn').onclick=()=>{document.body.classList.toggle('bright');toast('Theme preference changed.');};
